# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN python3 -m pip install pytest pytest-ansible pytest-xdist pytest-testinfra 
    
